language: java
arch:
  - amd64
  - ppc64le
jdk:
  - openjdk8
before_script:
  - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then sudo apt-get update; sudo apt-get install maven; fi
install: true
script: mvn test
